version: '3'
services:
  office:
    image: office
    ports:
      - "8081:8080"
  queue:
    image: queue
    ports:
      - "8082:8080"
  api:
    image: reboardingapi
    ports:
      - "8080:8080"
    depends_on:
      - office
      - queue
  